part of 'app_config.dart';

const defaultAppConfig = AppConfig(
  version: 1,
  debugMode: false,
  app: AppInfoConfig(
    displayName: 'FinTrack',
    logoAsset: 'assets/images/logoFinTrack.png',
    institution: 'Instituição indisponível.',
    author: 'Autor indisponível.',
    fallbackVersion: AppConfig.defaultAppVersionFallback,
  ),
  support: SupportConfig(
    email: '20212160060+Suporte_FinTrack@ifba.edu.br',
    reportSubject: '[FinTrack] Reporte de problema',
  ),
  about: AboutConfig(
    description: 'Informações do aplicativo indisponíveis.',
    howItWorks: 'Instruções de funcionamento indisponíveis.',
    privacy: 'Informações de privacidade indisponíveis.',
    openSource: 'Informações de código aberto indisponíveis.',
    features: <String>['Recursos indisponíveis.'],
    faq: <FaqConfig>[
      FaqConfig(
        question: 'FAQ indisponível',
        answer: 'Não foi possível carregar as dúvidas frequentes.',
      ),
    ],
  ),
  onboarding: OnboardingConfig(
    slides: <OnboardingSlideConfig>[
      OnboardingSlideConfig(
        icon: 'info',
        title: 'Boas-vindas',
        body: 'Não foi possível carregar as instruções iniciais.',
      ),
    ],
  ),
  ui: UiTextConfig(
    common: CommonTextConfig(
      apply: 'Aplicar',
      backup: 'Backup',
      cancel: 'Cancelar',
      clear: 'Limpar',
      close: 'Fechar',
      delete: 'Excluir',
      edit: 'Editar',
      restore: 'Restaurar',
      retry: 'Tentar novamente',
      save: 'Salvar',
      share: 'Compartilhar',
      saveToDevice: 'Salvar no dispositivo',
      shareOpened: 'Compartilhamento aberto.',
      shareFailed: 'Não foi possível abrir o compartilhamento.',
    ),
    backup: BackupTextConfig(
      loading: 'Carregando backup',
      loadError: 'Não foi possível carregar as configurações.',
      historyTitle: 'Histórico',
      clearHistoryTooltip: 'Apagar histórico',
      clearHistoryTitle: 'Apagar histórico de backup?',
      clearHistoryMessage:
          'Isso removerá apenas os registros exibidos nesta tela. Seus comprovantes, arquivos de backup e configurações não serão apagados.',
      clearHistoryAction: 'Apagar',
      historyCleared: 'Histórico de backup apagado.',
      googleLinked: 'Conta de nuvem vinculada.',
      unlinkGoogleTitle: 'Desvincular conta de nuvem',
      unlinkGoogleMessage:
          'Ao desvincular a conta de nuvem, o backup automático será desativado. Você confirma a desvinculação?',
      unlinkGoogleAction: 'Desvincular',
      googleUnlinked: 'Conta de nuvem desvinculada.',
      clearCloudTitle: 'Limpar dados da nuvem?',
      clearCloudMessage:
          'Esta ação removerá todos os dados do FinTrack armazenados no serviço de nuvem vinculado. O histórico local continuará disponível.',
      backupPasswordTitle: 'Senha do backup',
      clearCloudPasswordMessage:
          'Informe a senha do backup para autorizar a remoção dos dados da nuvem.',
      cloudDataCleared: 'Dados da nuvem removidos.',
      backupPasswordRequired:
          'Defina uma senha de backup nas configurações antes de fazer backup.',
      backupCompleted: 'Backup concluído.',
      backupInProgress: 'Fazendo backup',
      backupInProgressMessage:
          'Aguarde enquanto seus dados são preparados e enviados.',
      restoreTitle: 'Restaurar backup?',
      restoreMessage:
          'Os dados locais serão substituídos pelos dados do backup selecionado na nuvem.',
      restoreCompleted: 'Restauração concluída.',
      restoreInProgress: 'Restaurando backup',
      restoreInProgressMessage:
          'Aguarde enquanto seus dados locais são restaurados.',
      clearCloudInProgress: 'Removendo dados da nuvem',
      clearCloudInProgressMessage:
          'Aguarde enquanto os dados da nuvem são removidos.',
    ),
    receiptDetail: ReceiptDetailTextConfig(
      title: 'Detalhes',
      moreOptionsTooltip: 'Mais opções',
      loading: 'Carregando detalhes',
      loadError: 'Não foi possível abrir este comprovante.',
      summaryTitle: 'Resumo',
      dataTitle: 'Dados',
      establishment: 'Estabelecimento',
      value: 'Valor',
      nature: 'Natureza',
      expense: 'Despesa',
      income: 'Receita',
      date: 'Data',
      paymentMethod: 'Meio de pagamento',
      unidentified: 'Não identificado',
      receiptType: 'Tipo de comprovante',
      category: 'Categoria',
      withoutCategory: 'Sem categoria',
      synced: 'Sincronizado',
      local: 'Local',
      deleteTitle: 'Excluir comprovante?',
      deleteMessage:
          'A imagem, os dados e os dados de busca inteligente serão removidos.',
      deleted: 'Comprovante excluído.',
    ),
    receipts: ReceiptsTextConfig(
      confirmationLoading: 'Abrindo confirmação',
      confirmationNotFound: 'Comprovante não encontrado.',
      confirmationTitle: 'Confirmar dados',
      lowExtractionConfidence:
          'A extração automática ficou incerta. Revise os campos antes de salvar.',
      lowOcrConfidence:
          'A leitura automática ficou incerta. Revise os campos antes de salvar.',
      saveFailed: 'Não foi possível salvar o comprovante.',
      saved: 'Comprovante salvo com sucesso.',
      transactionDate: 'Data da transação',
      paymentMethodForm: 'Forma de pagamento',
      selectTransactionDate: 'Selecionar data da transação',
      clearDate: 'Limpar data',
      selectDate: 'Selecionar data',
      confirm: 'Confirmar',
      invalidDate: 'Data inválida',
      dateOutOfRange: 'Data fora do intervalo permitido',
      pendingFieldsTitle: 'Salvar com campos incompletos?',
      pendingFieldsMessage:
          'Os campos {fields} estão vazios ou com valor padrão. Isso pode dificultar encontrar este comprovante posteriormente.',
      review: 'Revisar',
      discardTitle: 'Descartar dados extraídos?',
      discardMessage:
          'Se você sair sem salvar, os dados extraídos e as alterações feitas nesta tela serão perdidos.',
      discard: 'Descartar',
      ocrResultTitle: 'Resultado do OCR',
      emptyOcrText: 'Nenhum texto identificado pelo OCR.',
      ocrTextTab: 'Texto',
      ocrStructuredTab: 'Estruturado',
      searchHint: 'Buscar comprovantes',
      searchHelper: 'Use filtros por categoria, período ou tipo.',
      diagnoseSemanticSearch: 'Diagnosticar busca semântica',
      clearSearch: 'Limpar busca',
      noImportFiles: 'Nenhum arquivo foi recebido para importação.',
      importFailed: 'Não foi possível importar o comprovante.',
      diagnoseFailed: 'Não foi possível diagnosticar a busca semântica.',
      files: ReceiptFilesTextConfig(
        fileSaved: 'Arquivo salvo no dispositivo.',
        filesSaved: 'Arquivos salvos no dispositivo.',
        fileSaveFailed: 'Não foi possível salvar o arquivo.',
        filesSaveFailed: 'Não foi possível salvar os arquivos.',
      ),
      deleted: 'Comprovante excluído.',
      deleteMany: '{total} comprovantes excluídos.',
      deleteFailed: 'Não foi possível excluir os comprovantes.',
      deletingSelection: 'Excluindo comprovantes',
      deletingSelectionMessage:
          'Aguarde enquanto os comprovantes selecionados são removidos.',
      moreOptions: 'Mais opções',
      shareSelected: 'Compartilhar selecionados',
      deleteSelected: 'Excluir selecionados',
      selectReceipts: 'Selecionar comprovantes',
      importReceipt: 'Importar comprovante',
      filters: 'Filtros',
      loadingReceipts: 'Carregando comprovantes',
      loadReceiptsFailed: 'Não foi possível carregar seus comprovantes.',
      loadMoreReceiptsFailed: 'Não foi possível carregar mais comprovantes.',
      searchingReceipts: 'Buscando comprovantes',
      searchFailed: 'Não foi possível executar a busca.',
      noSearchResults: 'Nenhum resultado encontrado',
      noReceipts: 'Nenhum comprovante registrado',
      noSearchResultsMessage:
          'Tente outros termos ou ajuste os filtros aplicados.',
      noReceiptsMessage:
          'Você também pode compartilhar comprovantes direto de outros apps.',
      selectedSingular: 'selecionado',
      selectedPlural: 'selecionados',
      all: 'Todos',
      allCategories: 'Todas',
      category: 'Categoria',
      withoutCategory: 'Sem categoria',
      expenses: 'Despesas',
      incomes: 'Receitas',
      period: 'Período',
      selectRange: 'Selecionar intervalo',
      clearPeriod: 'Limpar período',
      choosePeriod: 'Escolher período',
      start: 'Início',
      end: 'Fim',
      invalidRange: 'Intervalo inválido',
      invalidRangeOrder: 'A data final deve ser posterior à inicial',
      deleteSelectionTitleSingular: 'Excluir comprovante?',
      deleteSelectionTitlePlural: 'Excluir {total} comprovantes?',
      deleteSelectionMessage:
          'As imagens, os dados e os dados de busca inteligente serão removidos.',
    ),
    categories: KeyedTextConfig({
      'title': 'Categorias',
      'deleteSelectedTooltip': 'Excluir selecionadas',
      'selectCategoriesTooltip': 'Selecionar categorias',
      'loading': 'Carregando categorias',
      'loadError': 'Não foi possível carregar as categorias.',
      'usageLoadError': 'Não foi possível carregar o uso das categorias.',
      'reorderFailed': 'Não foi possível reordenar as categorias.',
      'newAction': 'Nova',
      'deleteOneTitle': 'Excluir categoria?',
      'deleteManyTitle': 'Excluir {total} categorias?',
      'deleteOneMessage': 'A categoria selecionada será removida.',
      'deleteManyMessage': 'As categorias selecionadas serão removidas.',
      'deletedOne': 'Categoria excluída.',
      'deletedMany': '{total} categorias excluídas.',
      'deletingSelection': 'Excluindo categorias',
      'deletingSelectionMessage':
          'Aguarde enquanto as categorias selecionadas são removidas.',
      'saved': 'Categoria salva.',
      'deleteNamedMessage': 'A categoria "{name}" será removida.',
      'categoryInUse': 'Categoria em uso',
      'categoriesInUse': 'Categorias em uso',
      'categoryInUseMessage':
          'A categoria "{names}" está associada a comprovantes. Desassocie essa categoria antes de excluí-la.',
      'categoriesInUseMessage':
          'Existem categorias selecionadas associadas a comprovantes: {names}. Desassocie essas categorias antes de excluí-las.',
      'viewReceipts': 'Ver comprovantes',
      'understood': 'Entendi',
      'newDialogTitle': 'Nova categoria',
      'editDialogTitle': 'Editar categoria',
      'name': 'Nome',
      'description': 'Descrição',
      'nameRequired': 'Informe um nome',
      'descriptionHelper':
          'Use a descrição para indicar exemplos, termos recorrentes e limites da categoria. Ela ajuda a leitura dos comprovantes e deixa a classificação mais previsível.',
      'emptySearchTitle': 'Nenhuma categoria encontrada',
      'emptySearchMessage': 'Tente buscar por outro nome ou descrição.',
      'emptyTitle': 'Nenhuma categoria cadastrada',
      'emptyMessage':
          'Crie categorias para organizar comprovantes e melhorar os relatórios.',
      'dragToReorder': 'Arrastar para reordenar',
      'searchHint': 'Buscar categoria',
      'clearSearch': 'Limpar busca',
      'selectedSingular': 'selecionada',
      'selectedPlural': 'selecionadas',
      'countSingular': 'categoria',
      'countPlural': 'categorias',
      'all': 'Todos',
      'filterLabelPrefix': 'Categoria',
    }),
    configuration: KeyedTextConfig({
      'title': 'Configurações',
      'loading': 'Carregando configurações',
      'loadError': 'Não foi possível abrir as configurações.',
      'localAuthEnabled': 'Autenticação local ativada.',
      'localAuthDisabled': 'Autenticação local desativada.',
      'disableLocalAuthReason':
          'Confirme sua identidade para desativar a autenticação local.',
      'backupAutoEnabled': 'Backup automático definido.',
      'backupAutoDisabled': 'Backup automático desativado.',
      'backupAutoFailed': 'Não foi possível configurar o backup automático.',
      'backupPasswordUpdated': 'Senha de backup atualizada.',
      'backupPasswordRemoved':
          'Senha de backup removida. Defina outra para reativar backups automáticos.',
      'changeAuthReason':
          'Confirme sua identidade para alterar a proteção local.',
      'authMethodUpdated': 'Método de autenticação atualizado.',
      'tutorialReset': 'Tutorial reiniciado.',
      'pinConfigIncompleteEnable':
          'Configuração do PIN não concluída. A autenticação local não foi ativada.',
      'pinConfigIncompleteKeep':
          'Configuração do PIN não concluída. O método anterior foi mantido.',
      'backupSection': 'Configurações de backup',
      'backupSubtitle': 'Nuvem e histórico de sincronização.',
      'backupPassword': 'Senha de backup',
      'backupPasswordDefined': 'Altere a senha usada nos backups.',
      'backupPasswordDefine': 'Crie uma senha para seus backups.',
      'removePassword': 'Remover senha',
      'automaticBackup': 'Backup automático',
      'automaticBackupSubtitle': 'Configure backups automáticos.',
      'openBackup': 'Abrir Backup',
      'automaticBackupInterval': 'Intervalo do backup automático',
      'storageSection': 'Consumo de espaço e limites',
      'storageLimit': 'Limite de armazenamento',
      'authSection': 'Proteção do aplicativo',
      'localAuth': 'Autenticação local',
      'localAuthSubtitle': 'Proteja o acesso com PIN ou biometria.',
      'selectMethod': 'Escolha um método',
      'authType': 'Método de proteção',
      'autoLock': 'Bloqueio automático',
      'changePin': 'Alterar PIN',
      'changePinSubtitle': 'Atualize o código de acesso.',
      'infoSection': 'Informações da aplicação',
      'viewTutorial': 'Ver tutorial',
      'viewTutorialSubtitle': 'Veja novamente o tutorial do aplicativo.',
      'aboutTitle': 'Sobre o FinTrack',
      'aboutSubtitle': 'Propósito, privacidade, funcionamento e FAQ.',
      'passwordRequiredTitle': 'Senha necessária',
      'passwordRequiredMessage':
          'Para ativar o backup automático, defina uma senha de backup primeiro.',
      'exitTitle': 'Sair do FinTrack?',
      'exitMessage': 'O aplicativo será fechado.',
      'exitAction': 'Sair',
      'chooseProtection': 'Escolha a proteção',
      'pinSubtitle': 'Código numérico criado no dispositivo',
      'biometric': 'Biometria',
      'biometricSubtitle': 'Use a biometria cadastrada no aparelho',
      'setBackupPasswordTitle': 'Definir senha de backup',
      'changeBackupPasswordTitle': 'Alterar senha de backup',
      'backupPasswordHelp':
          'Essa senha protege seus backups. Se você esquecê-la, não será possível restaurar arquivos protegidos por ela.',
      'currentPassword': 'Senha atual',
      'newPassword': 'Nova senha',
      'confirmNewPassword': 'Confirmar nova senha',
      'showPassword': 'Mostrar senha',
      'hidePassword': 'Ocultar senha',
      'wrongCurrentPassword': 'Senha atual incorreta.',
      'passwordMismatch': 'As senhas não conferem.',
      'passwordTooShort': 'Use pelo menos 8 caracteres.',
      'passwordSameAsCurrent': 'Use uma senha diferente da atual.',
      'removeBackupPasswordTitle': 'Remover senha de backup?',
      'removeBackupPasswordMessage':
          'Informe a senha atual. A senha será removida e o backup automático será desativado até uma nova senha ser definida.',
      'remove': 'Remover',
    }),
    authentication: KeyedTextConfig({
      'pinSaveFailed': 'Não foi possível salvar o PIN de forma segura.',
      'enableBiometricTitle': 'Ativar biometria',
      'enableBiometricSubtitle':
          'Confirme sua identidade para ativar a proteção.',
      'biometricNotConfirmed': 'A biometria não foi confirmada.',
      'defaultReason': 'Confirme sua identidade para acessar o FinTrack.',
      'wrongPin': 'PIN incorreto. Acesso não autorizado.',
      'unlockTitle': 'Desbloquear FinTrack',
      'biometricFailed':
          'Não foi possível confirmar a biometria. Acesso não autorizado.',
      'confirmPinTitle': 'Confirmar PIN',
      'createPinTitle': 'Criar PIN',
      'repeatPin': 'Digite o PIN novamente.',
      'pinInstructions': 'Informe um código numérico de 4 a 12 dígitos.',
      'pin': 'PIN',
      'savePin': 'Salvar PIN',
      'continue': 'Continuar',
      'pinTooShort': 'Informe ao menos 4 dígitos.',
      'pinMismatch': 'Os PINs não conferem. Comece novamente.',
      'unlock': 'Desbloquear',
      'pinRequired': 'Informe o PIN cadastrado.',
    }),
  ),
);
