// Mocks generated by Mockito 5.4.6 from annotations
// in fin_track/test/widget/presentation_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i2;

import 'package:fin_track/domain/entities/backup_record.dart' as _i4;
import 'package:fin_track/domain/entities/cloud_provider.dart' as _i13;
import 'package:fin_track/domain/entities/configuration.dart' as _i5;
import 'package:fin_track/domain/entities/receipt.dart' as _i3;
import 'package:fin_track/domain/infrastructure/i_local_authentication_service.dart'
    as _i14;
import 'package:fin_track/domain/services/i_backup_service.dart' as _i11;
import 'package:fin_track/domain/services/i_configuration_service.dart' as _i12;
import 'package:fin_track/domain/services/i_receipt_service.dart' as _i7;
import 'package:fin_track/domain/value_objects/biometric_status.dart' as _i6;
import 'package:fin_track/domain/value_objects/receipt_filter.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFile_0 extends _i1.SmartFake implements _i2.File {
  _FakeFile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReceipt_1 extends _i1.SmartFake implements _i3.Receipt {
  _FakeReceipt_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBackupRecord_2 extends _i1.SmartFake implements _i4.BackupRecord {
  _FakeBackupRecord_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfiguration_3 extends _i1.SmartFake implements _i5.Configuration {
  _FakeConfiguration_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBiometricStatus_4 extends _i1.SmartFake
    implements _i6.BiometricStatus {
  _FakeBiometricStatus_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IReceiptService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIReceiptService extends _i1.Mock implements _i7.IReceiptService {
  @override
  _i8.Future<_i2.File> scanDocument() =>
      (super.noSuchMethod(
            Invocation.method(#scanDocument, []),
            returnValue: _i8.Future<_i2.File>.value(
              _FakeFile_0(this, Invocation.method(#scanDocument, [])),
            ),
            returnValueForMissingStub: _i8.Future<_i2.File>.value(
              _FakeFile_0(this, Invocation.method(#scanDocument, [])),
            ),
          )
          as _i8.Future<_i2.File>);

  @override
  _i8.Future<_i2.File> captureImage() =>
      (super.noSuchMethod(
            Invocation.method(#captureImage, []),
            returnValue: _i8.Future<_i2.File>.value(
              _FakeFile_0(this, Invocation.method(#captureImage, [])),
            ),
            returnValueForMissingStub: _i8.Future<_i2.File>.value(
              _FakeFile_0(this, Invocation.method(#captureImage, [])),
            ),
          )
          as _i8.Future<_i2.File>);

  @override
  _i8.Future<List<_i2.File>> importFiles() =>
      (super.noSuchMethod(
            Invocation.method(#importFiles, []),
            returnValue: _i8.Future<List<_i2.File>>.value(<_i2.File>[]),
            returnValueForMissingStub: _i8.Future<List<_i2.File>>.value(
              <_i2.File>[],
            ),
          )
          as _i8.Future<List<_i2.File>>);

  @override
  _i8.Future<void> validateSpaceForNewReceipt([_i2.File? file]) =>
      (super.noSuchMethod(
            Invocation.method(#validateSpaceForNewReceipt, [file]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> validateSpaceForNewReceipts(List<_i2.File>? files) =>
      (super.noSuchMethod(
            Invocation.method(#validateSpaceForNewReceipts, [files]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.Receipt> processPreview(_i2.File? image) =>
      (super.noSuchMethod(
            Invocation.method(#processPreview, [image]),
            returnValue: _i8.Future<_i3.Receipt>.value(
              _FakeReceipt_1(this, Invocation.method(#processPreview, [image])),
            ),
            returnValueForMissingStub: _i8.Future<_i3.Receipt>.value(
              _FakeReceipt_1(this, Invocation.method(#processPreview, [image])),
            ),
          )
          as _i8.Future<_i3.Receipt>);

  @override
  _i8.Future<_i3.Receipt> saveConfirmed(_i3.Receipt? receipt) =>
      (super.noSuchMethod(
            Invocation.method(#saveConfirmed, [receipt]),
            returnValue: _i8.Future<_i3.Receipt>.value(
              _FakeReceipt_1(
                this,
                Invocation.method(#saveConfirmed, [receipt]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.Receipt>.value(
              _FakeReceipt_1(
                this,
                Invocation.method(#saveConfirmed, [receipt]),
              ),
            ),
          )
          as _i8.Future<_i3.Receipt>);

  @override
  _i8.Future<void> discardPreview(_i3.Receipt? receipt) =>
      (super.noSuchMethod(
            Invocation.method(#discardPreview, [receipt]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.Receipt> register(_i2.File? image) =>
      (super.noSuchMethod(
            Invocation.method(#register, [image]),
            returnValue: _i8.Future<_i3.Receipt>.value(
              _FakeReceipt_1(this, Invocation.method(#register, [image])),
            ),
            returnValueForMissingStub: _i8.Future<_i3.Receipt>.value(
              _FakeReceipt_1(this, Invocation.method(#register, [image])),
            ),
          )
          as _i8.Future<_i3.Receipt>);

  @override
  _i8.Future<_i2.File> localFile(_i3.Receipt? receipt) =>
      (super.noSuchMethod(
            Invocation.method(#localFile, [receipt]),
            returnValue: _i8.Future<_i2.File>.value(
              _FakeFile_0(this, Invocation.method(#localFile, [receipt])),
            ),
            returnValueForMissingStub: _i8.Future<_i2.File>.value(
              _FakeFile_0(this, Invocation.method(#localFile, [receipt])),
            ),
          )
          as _i8.Future<_i2.File>);

  @override
  _i8.Future<List<_i3.Receipt>> search(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: _i8.Future<List<_i3.Receipt>>.value(<_i3.Receipt>[]),
            returnValueForMissingStub: _i8.Future<List<_i3.Receipt>>.value(
              <_i3.Receipt>[],
            ),
          )
          as _i8.Future<List<_i3.Receipt>>);

  @override
  _i8.Future<List<_i3.Receipt>> findByFilters(_i9.ReceiptFilter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#findByFilters, [filter]),
            returnValue: _i8.Future<List<_i3.Receipt>>.value(<_i3.Receipt>[]),
            returnValueForMissingStub: _i8.Future<List<_i3.Receipt>>.value(
              <_i3.Receipt>[],
            ),
          )
          as _i8.Future<List<_i3.Receipt>>);

  @override
  _i8.Future<_i3.Receipt> findById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#findById, [id]),
            returnValue: _i8.Future<_i3.Receipt>.value(
              _FakeReceipt_1(this, Invocation.method(#findById, [id])),
            ),
            returnValueForMissingStub: _i8.Future<_i3.Receipt>.value(
              _FakeReceipt_1(this, Invocation.method(#findById, [id])),
            ),
          )
          as _i8.Future<_i3.Receipt>);

  @override
  _i8.Future<void> update(_i3.Receipt? receipt) =>
      (super.noSuchMethod(
            Invocation.method(#update, [receipt]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> deleteOrphanFiles() =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrphanFiles, []),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<_i2.File> exportFile(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#exportFile, [id]),
            returnValue: _i8.Future<_i2.File>.value(
              _FakeFile_0(this, Invocation.method(#exportFile, [id])),
            ),
            returnValueForMissingStub: _i8.Future<_i2.File>.value(
              _FakeFile_0(this, Invocation.method(#exportFile, [id])),
            ),
          )
          as _i8.Future<_i2.File>);

  @override
  _i8.Future<void> shareImage(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#shareImage, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> shareImages(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#shareImages, [ids]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveImageToDevice(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#saveImageToDevice, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveImagesToDevice(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#saveImagesToDevice, [ids]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> reindexPendingSemanticEmbeddings() =>
      (super.noSuchMethod(
            Invocation.method(#reindexPendingSemanticEmbeddings, []),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<String> diagnoseSemanticSearch(String? query, {int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(
              #diagnoseSemanticSearch,
              [query],
              {#limit: limit},
            ),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(
                  #diagnoseSemanticSearch,
                  [query],
                  {#limit: limit},
                ),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(
                  #diagnoseSemanticSearch,
                  [query],
                  {#limit: limit},
                ),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Stream<List<_i3.Receipt>> watchByFilters(_i9.ReceiptFilter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#watchByFilters, [filter]),
            returnValue: _i8.Stream<List<_i3.Receipt>>.empty(),
            returnValueForMissingStub: _i8.Stream<List<_i3.Receipt>>.empty(),
          )
          as _i8.Stream<List<_i3.Receipt>>);

  @override
  _i8.Stream<List<_i3.Receipt>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i8.Stream<List<_i3.Receipt>>.empty(),
            returnValueForMissingStub: _i8.Stream<List<_i3.Receipt>>.empty(),
          )
          as _i8.Stream<List<_i3.Receipt>>);
}

/// A class which mocks [IBackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBackupService extends _i1.Mock implements _i11.IBackupService {
  @override
  _i8.Future<_i4.BackupRecord> exportBackup({required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#exportBackup, [], {#password: password}),
            returnValue: _i8.Future<_i4.BackupRecord>.value(
              _FakeBackupRecord_2(
                this,
                Invocation.method(#exportBackup, [], {#password: password}),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i4.BackupRecord>.value(
              _FakeBackupRecord_2(
                this,
                Invocation.method(#exportBackup, [], {#password: password}),
              ),
            ),
          )
          as _i8.Future<_i4.BackupRecord>);

  @override
  _i8.Future<_i4.BackupRecord?> runAutomaticBackupIfNeeded({DateTime? now}) =>
      (super.noSuchMethod(
            Invocation.method(#runAutomaticBackupIfNeeded, [], {#now: now}),
            returnValue: _i8.Future<_i4.BackupRecord?>.value(),
            returnValueForMissingStub: _i8.Future<_i4.BackupRecord?>.value(),
          )
          as _i8.Future<_i4.BackupRecord?>);

  @override
  _i8.Future<_i4.BackupRecord> restoreBackup({required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#restoreBackup, [], {#password: password}),
            returnValue: _i8.Future<_i4.BackupRecord>.value(
              _FakeBackupRecord_2(
                this,
                Invocation.method(#restoreBackup, [], {#password: password}),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i4.BackupRecord>.value(
              _FakeBackupRecord_2(
                this,
                Invocation.method(#restoreBackup, [], {#password: password}),
              ),
            ),
          )
          as _i8.Future<_i4.BackupRecord>);

  @override
  _i8.Future<List<_i4.BackupRecord>> listRecords() =>
      (super.noSuchMethod(
            Invocation.method(#listRecords, []),
            returnValue: _i8.Future<List<_i4.BackupRecord>>.value(
              <_i4.BackupRecord>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i4.BackupRecord>>.value(
              <_i4.BackupRecord>[],
            ),
          )
          as _i8.Future<List<_i4.BackupRecord>>);

  @override
  _i8.Stream<List<_i4.BackupRecord>> watchRecords() =>
      (super.noSuchMethod(
            Invocation.method(#watchRecords, []),
            returnValue: _i8.Stream<List<_i4.BackupRecord>>.empty(),
            returnValueForMissingStub:
                _i8.Stream<List<_i4.BackupRecord>>.empty(),
          )
          as _i8.Stream<List<_i4.BackupRecord>>);

  @override
  _i8.Future<void> clearHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearHistory, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteBackup({required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBackup, [], {#password: password}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [IConfigurationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIConfigurationService extends _i1.Mock
    implements _i12.IConfigurationService {
  @override
  _i8.Future<_i5.Configuration> load() =>
      (super.noSuchMethod(
            Invocation.method(#load, []),
            returnValue: _i8.Future<_i5.Configuration>.value(
              _FakeConfiguration_3(this, Invocation.method(#load, [])),
            ),
            returnValueForMissingStub: _i8.Future<_i5.Configuration>.value(
              _FakeConfiguration_3(this, Invocation.method(#load, [])),
            ),
          )
          as _i8.Future<_i5.Configuration>);

  @override
  _i8.Future<void> update(_i5.Configuration? configuration) =>
      (super.noSuchMethod(
            Invocation.method(#update, [configuration]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> linkCloud(_i13.CloudProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkCloud, [provider]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> unlinkCloud() =>
      (super.noSuchMethod(
            Invocation.method(#unlinkCloud, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> verifyCloudToken() =>
      (super.noSuchMethod(
            Invocation.method(#verifyCloudToken, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> linkGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#linkGoogle, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> unlinkGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#unlinkGoogle, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> verifyGoogleToken() =>
      (super.noSuchMethod(
            Invocation.method(#verifyGoogleToken, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> configureAutomaticBackup({
    required bool? active,
    required int? intervalDays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#configureAutomaticBackup, [], {
              #active: active,
              #intervalDays: intervalDays,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> normalizeAutomaticBackupIfNeeded() =>
      (super.noSuchMethod(
            Invocation.method(#normalizeAutomaticBackupIfNeeded, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> calculateUsedSpaceBytes() =>
      (super.noSuchMethod(
            Invocation.method(#calculateUsedSpaceBytes, []),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<void> completeOnboarding() =>
      (super.noSuchMethod(
            Invocation.method(#completeOnboarding, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> resetOnboarding() =>
      (super.noSuchMethod(
            Invocation.method(#resetOnboarding, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<_i5.Configuration> watch() =>
      (super.noSuchMethod(
            Invocation.method(#watch, []),
            returnValue: _i8.Stream<_i5.Configuration>.empty(),
            returnValueForMissingStub: _i8.Stream<_i5.Configuration>.empty(),
          )
          as _i8.Stream<_i5.Configuration>);
}

/// A class which mocks [ILocalAuthenticationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocalAuthenticationService extends _i1.Mock
    implements _i14.ILocalAuthenticationService {
  @override
  _i8.Future<bool> savePin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#savePin, [pin]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> authenticatePin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#authenticatePin, [pin]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> removePin() =>
      (super.noSuchMethod(
            Invocation.method(#removePin, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i6.BiometricStatus> checkBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#checkBiometrics, []),
            returnValue: _i8.Future<_i6.BiometricStatus>.value(
              _FakeBiometricStatus_4(
                this,
                Invocation.method(#checkBiometrics, []),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.BiometricStatus>.value(
              _FakeBiometricStatus_4(
                this,
                Invocation.method(#checkBiometrics, []),
              ),
            ),
          )
          as _i8.Future<_i6.BiometricStatus>);

  @override
  _i8.Future<bool> authenticateBiometrics({
    required String? title,
    required String? subtitle,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authenticateBiometrics, [], {
              #title: title,
              #subtitle: subtitle,
            }),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}
